export const CONFIG = {
  meta: {
    version: "0.3.0",
    experiment_id: "baseline",
  },
  economy: {
    revenue_tick_ms: 1000,
    starting_money: 0,
    public_grid_cost_per_kwh: 0.30,
    public_grid_cap_kw: 5,
    energy_cost_per_kwh: {
      coal: 0.04, oil: 0.07, solar: 0.00, nuclear: 0.02, fusion: 0.00,
    },
    capability_tiers: [
      { min_tokens_trained: 0,    price_per_million: 0.10 },
      { min_tokens_trained: 1e9,  price_per_million: 0.50 },
      { min_tokens_trained: 1e11, price_per_million: 2.00 },
      { min_tokens_trained: 1e12, price_per_million: 8.00 },
      { min_tokens_trained: 1e13, price_per_million: 30.00 },
    ],
    data_quality_multipliers: {
      raw: 1.0, pipeline_cleaned: 3.0, rlhf_labeled: 8.0, synthetic: 15.0,
    },
  },
  buildings: {
    rtx_3090: {
      base_cost: 1500, cost_multiplier: 1.12,
      tflops_fp16: 35.6, tdp_kw: 0.35, unlock_phase: 1,
      label: "RTX 3090", category: "compute",
      tooltip: "A consumer gaming card repurposed for training. 24GB VRAM, 350W. Early OpenAI and Stability AI prototypes ran on these. Not efficient, but you have to start somewhere.",
    },
    rtx_4090: {
      base_cost: 2500, cost_multiplier: 1.12,
      tflops_fp16: 82.6, tdp_kw: 0.45, unlock_phase: 1,
      label: "RTX 4090", category: "compute",
      unlock_requires: { rtx_3090: 4 },
      tooltip: "The most powerful consumer GPU ever made. 24GB VRAM, 450W. About 2.3× faster than a 3090. The go-to card before you can afford datacenter hardware.",
    },
    h100_sxm: {
      base_cost: 30000, cost_multiplier: 1.10,
      tflops_fp16: 1979, tdp_kw: 0.70, unlock_phase: 2,
      label: "H100 SXM", category: "compute",
      unlock_requires: { colo_rack: 1 },
      tooltip: "The card that runs the frontier. 80GB HBM3, NVLink for multi-GPU. One H100 has ~24× the training throughput of an RTX 4090.",
    },
    dgx_h100: {
      base_cost: 250000, cost_multiplier: 1.15,
      tflops_fp16: 15832, tdp_kw: 6.4, unlock_phase: 2,
      label: "DGX H100", category: "compute",
      unlock_requires: { h100_sxm: 8 },
      tooltip: "NVIDIA's pre-built 8-GPU server. NVLink connects all 8 GPUs at 900 GB/s — 9× faster than PCIe.",
    },
    gb200_nvl72: {
      base_cost: 3000000, cost_multiplier: 1.20,
      tflops_fp16: 1440000, tdp_kw: 120, unlock_phase: 4,
      label: "GB200 NVL72", category: "compute",
      tooltip: "A full Blackwell rack: 36 Grace CPUs + 72 B200 GPUs on NVLink Switch. One rack does what used to need a warehouse of H100s.",
    },
    tpu_v5p: {
      base_cost: 8000000, cost_multiplier: 1.25,
      tflops_fp16: 459000, tdp_kw: 460, unlock_phase: 4,
      label: "TPU v5p Pod", category: "compute",
      tooltip: "Google's custom training chip. Less flexible than GPUs, but better FLOP/$ for pure training. Gemini was trained on these.",
    },
    orbital_datacenter: {
      base_cost: 10000000000, cost_multiplier: 1.50,
      tflops_fp16: 50000000, tdp_kw: 0, unlock_phase: 5,
      label: "Orbital Datacenter", category: "compute",
      tooltip: "Solar power in orbit, radiative cooling into the void. 250ms latency to Earth — fine for training.",
    },
    web_scraper: {
      base_cost: 5000, cost_multiplier: 1.20,
      tokens_per_second: 5787, recurring_cost_per_s: 0.002, unlock_phase: 2,
      label: "Web Scraper", category: "data",
      tooltip: "Crawls the internet and downloads text. Raw output is messy: duplicates, spam, HTML noise. Needs a Data Pipeline to be usable for training.",
    },
    data_pipeline: {
      base_cost: 20000, cost_multiplier: 1.15,
      yield_multiplier: 3.0, recurring_cost_per_s: 0.005, unlock_phase: 2,
      label: "Data Pipeline", category: "data",
      unlock_requires: { web_scraper: 1 },
      tooltip: "Deduplication (MinHash), quality filtering (perplexity scoring), boilerplate removal. 15% yield sounds bad but quality beats quantity.",
    },
    colo_rack: {
      base_cost: 10000, cost_multiplier: 1.10,
      recurring_cost_per_s: 0.006, unlock_phase: 2,
      label: "Colocation Rack", category: "infrastructure",
      tooltip: "Renting space in a professional datacenter. Required for anything beyond consumer cards.",
    },
    owned_datacenter: {
      base_cost: 10000000, cost_multiplier: 1.0,
      unlock_phase: 3,
      label: "Owned Datacenter", category: "infrastructure",
      tooltip: "You own the building. Eliminates all rack rental costs. +5% compute efficiency.",
    },
    coal_plant: {
      base_cost: 30000, cost_multiplier: 1.0,
      capacity_mw: 200, cost_per_kwh: 0.04, unlock_phase: 2,
      label: "Coal Plant", category: "energy",
      tooltip: "Cheap to build, cheap fuel. No in-game penalty beyond the fuel cost.",
    },
    oil_generator: {
      base_cost: 50000, cost_multiplier: 1.0,
      capacity_mw: 150, cost_per_kwh: 0.07, unlock_phase: 2,
      label: "Oil Generator", category: "energy",
      tooltip: "Diesel/heavy oil generation. More expensive per kWh than coal but faster to deploy.",
    },
    solar_farm: {
      base_cost: 500000, cost_multiplier: 1.0,
      capacity_mw: 200, cost_per_kwh: 0.00, unlock_phase: 3,
      label: "Solar Farm", category: "energy",
      tooltip: "High upfront, zero marginal cost. Microsoft and Google have signed massive solar PPAs to power AI datacenters.",
    },
    nuclear_fission: {
      base_cost: 5000000, cost_multiplier: 1.0,
      capacity_mw: 1000, cost_per_kwh: 0.02, unlock_phase: 3,
      label: "Nuclear Fission Reactor", category: "energy",
      tooltip: "Reliable baseload, near-zero carbon. Microsoft restarted Three Mile Island specifically for AI datacenter power.",
    },
    fusion_reactor: {
      base_cost: 1000000000, cost_multiplier: 1.0,
      capacity_mw: 10000, cost_per_kwh: 0.00, unlock_phase: 5,
      label: "Fusion Reactor", category: "energy",
      tooltip: "Always 20 years away — until now. Unlimited clean energy, zero fuel cost.",
    },
  },
  techniques: {
    mixed_precision_fp16: { cost: 10000, phase: 2, label: "Mixed Precision FP16", effect: "compute_multiplier", value: 1.40, tooltip: "Storing numbers in 16-bit instead of 32-bit halves memory and speeds matrix math." },
    gradient_checkpointing: { cost: 15000, phase: 2, label: "Gradient Checkpointing", effect: "vram_multiplier", value: 0.50, tooltip: "Recompute intermediate values during backward pass instead of storing them." },
    flash_attention: { cost: 25000, phase: 2, label: "Flash Attention", effect: "speed_multiplier", value: 1.10, tooltip: "Processes attention in tiles that fit in fast SRAM, avoiding slow GPU memory reads." },
    adamw_optimizer: { cost: 5000, phase: 2, label: "AdamW Optimizer", effect: "quality_per_run", value: 0.05, tooltip: "Adaptive learning rates per parameter plus weight decay. Standard for LLM training since GPT-2." },
    cosine_lr_schedule: { cost: 8000, phase: 2, label: "Cosine LR Schedule", effect: "overfitting_reduction", value: 0.10, tooltip: "Decays learning rate following a cosine curve." },
    gradient_clipping: { cost: 3000, phase: 2, label: "Gradient Clipping", effect: "stability", value: 1.0, tooltip: "Clips gradient norm to a maximum value. Prevents a single bad batch from destabilizing the whole run." },
    zero_stage_1: { cost: 100000, phase: 3, label: "ZeRO Stage 1", effect: "memory_reduction", value: 0.25, tooltip: "Shards optimizer states across GPUs." },
    zero_stage_2: { cost: 200000, phase: 3, label: "ZeRO Stage 2", effect: "memory_reduction", value: 0.40, tooltip: "Adds gradient sharding to ZeRO-1." },
    zero_stage_3: { cost: 500000, phase: 3, label: "ZeRO Stage 3", effect: "unlimited_model_size", value: 1.0, tooltip: "Full parameter sharding. Train models of arbitrary size." },
    mixture_of_experts: { cost: 800000, phase: 3, label: "Mixture of Experts", effect: "capacity_multiplier", value: 4.0, tooltip: "Routes each token to a subset of expert sub-networks. DeepSeek-V3 uses 256 experts; each token activates 8." },
    knowledge_distillation: { cost: 300000, phase: 3, label: "Knowledge Distillation", effect: "unlocks_distillation", value: 1.0, tooltip: "Train a small student model on your large teacher's output distribution." },
    bf16_training: { cost: 20000, phase: 3, label: "BF16 Training", effect: "stability", value: 1.0, tooltip: "Same exponent range as FP32 but fewer mantissa bits. Google invented it for TPUs." },
    fp8_training: { cost: 150000, phase: 3, label: "FP8 Training", effect: "compute_multiplier", value: 2.0, tooltip: "Ultra-low precision on Hopper/Blackwell. Halves FLOP count for matrix multiplications." },
    rlhf: { cost: 200000, phase: 3, label: "RLHF", effect: "quality_multiplier", value: 1.0, tooltip: "Trains a reward model on preference pairs. How ChatGPT went from technically impressive to actually useful." },
    grouped_query_attention: { cost: 400000, phase: 4, label: "Grouped-Query Attention", effect: "kv_cache_reduction", value: 0.60, tooltip: "Groups of query heads share key/value heads. Used in Llama 3 and Mistral." },
    speculative_decoding: { cost: 600000, phase: 4, label: "Speculative Decoding", effect: "inference_throughput", value: 2.5, tooltip: "A small draft model proposes several tokens; the big model verifies them all in one pass." },
    continuous_batching: { cost: 100000, phase: 4, label: "Continuous Batching", effect: "gpu_utilization", value: 1.40, tooltip: "Requests join and leave the inference batch dynamically." },
    int8_quantization: { cost: 180000, phase: 4, label: "INT8 Quantization", effect: "inference_compute", value: 0.50, tooltip: "Round weights from 32-bit floats to 8-bit integers post-training." },
  },
  minigames: {
    bpe: {
      enabled: true, corpus_length_chars: 200,
      target_merges: 50, perfect_bonus: 1.15, avg_bonus: 1.05,
    },
    data_labeling: {
      enabled: true,
      pay_per_correct: 15,
      grid_size: 3,
      round_time_ms: 4000,
      target_min_count: 3,
      target_max_count: 5,
    },
    hyperparameter_tuning: {
      enabled: true,
      slider_unlock_order: ["learning_rate","batch_size","warmup_steps","weight_decay","training_duration"],
      optimal_bonus: 0.30, automl_accuracy: 0.95, automl_cost: 50000,
    },
    pipeline_scheduler: {
      enabled: true,
      levels: [
        { stages: 4, timesteps: 8,  microbatches: 4  },
        { stages: 8, timesteps: 16, microbatches: 8  },
        { stages: 16, timesteps: 32, microbatches: 16 },
      ],
      ilp_automation_cost: 200000,
    },
    benchmark_eval: {
      enabled: true,
      question_pools: ["mmlu","hellaswag","arc","gsm8k"],
      questions_per_run: 10, time_limit_s: 30,
      score_thresholds: { tier3: 0.60, tier4: 0.75, tier5: 0.90 },
      auto_refresh_ms: 300000, auto_eval_cost: 80000,
      contamination_bonus: 0.07,
    },
  },
  phase_thresholds: {
    phase_2: { min_money_ever: 1500 },
    phase_3: { min_compute_tflops: 500 },
    phase_4: { min_tokens_trained: 1e11 },
    phase_5: { min_tokens_trained: 1e12 },
  },
  token_stream: {
    manual_click_tokens_phase1: 50,
    blur_threshold_tps: 10000,
    waterfall_threshold_tps: 100000,
  },
  save: {
    autosave_interval_ms: 30000,
    offline_cap_hours: 8,
    offline_training_enabled: false,
    localstorage_key: "agi_incremental_save_v1",
  },
  audio: {
    sfx_volume: 0.60, bgm_volume: 0.40, muted: false,
  },
  posthog: { enabled: true, api_key: "" },
} as const
